apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: budget
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: Budgy_development
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rails-secret
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rails-secret
              key: postgres_password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: budget
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
